# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lboieru <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/15 21:41:36 by lboieru           #+#    #+#              #
#    Updated: 2015/09/15 21:52:42 by lboieru          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op
FLAGS = -Wall -Wextra -Werror
EX = do-op
OPTIONS = -o do-op
SRCS = main.c functions.c operations.c

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(OPTIONS) $(SRCS)

clean:
	rm $(EX)
