# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acoporii <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/09/19 19:36:49 by acoporii          #+#    #+#              #
#    Updated: 2015/09/23 16:47:38 by ohoza            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC	= *.c

NAME	= bsq

FLAGS	= -Werror -Wall -Wextra

all:	$(NAME)

$(NAME):
	gcc $(SRC) $(FLAGC) -o $(NAME)

fclean:	
	rm -f $(NAME)

re:	fclean all
